"""Fixture and golden loading, plus deterministic synthetic-data generators.

All committed fixtures are unmistakably synthetic: every person, employer,
date, and event in them is fictional. ``build_journal`` and
``build_neutral_pool`` are pure functions of their inputs, so the committed
``neutral_pool.jsonl`` can be regenerated byte-for-byte (``validate`` checks
this).
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from .chunking import chunk_text
from .config import BENCH_ROOT

FIXTURES = BENCH_ROOT / "fixtures"
GOLDENS = BENCH_ROOT / "goldens"
PROMPTS = BENCH_ROOT / "prompts"


def load_jsonl(path: Path) -> list[dict]:
    records = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            records.append(json.loads(line))
    return records


@lru_cache(maxsize=None)
def load_retain_fixture(name: str) -> list[dict]:
    return load_jsonl(FIXTURES / "retain" / f"{name}.jsonl")


@lru_cache(maxsize=None)
def load_retrieval_fixture(name: str) -> list[dict]:
    return load_jsonl(FIXTURES / "retrieval" / f"{name}.jsonl")


@lru_cache(maxsize=None)
def load_golden(name: str) -> dict:
    return json.loads((GOLDENS / f"{name}.json").read_text(encoding="utf-8"))


@lru_cache(maxsize=None)
def load_journal_generator() -> dict:
    return json.loads((FIXTURES / "journal" / "generator.json").read_text(encoding="utf-8"))


@lru_cache(maxsize=None)
def load_journal_expected() -> dict:
    return json.loads((FIXTURES / "journal" / "expected_facts.json").read_text(encoding="utf-8"))


@lru_cache(maxsize=None)
def load_prompt(name: str = "hindsight-v0.9.2-extraction") -> str:
    return (PROMPTS / f"{name}.md").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Deterministic synthetic data builders
# ---------------------------------------------------------------------------

NEUTRAL_TEMPLATES = (
    "Project Orion deployment note {i}: the staging health check passed after a routine restart.",
    "Security review item {i}: an S3 bucket policy was examined and no public access was found.",
    "Development log {i}: the frontend build completed and unit tests passed.",
    "Operations note {i}: a backup completed successfully on the media server.",
    "Meeting note {i}: the team discussed documentation formatting and code review timing.",
    "Cloud audit record {i}: an IAM role was inventoried in the test account.",
    "Personal note {i}: a grocery list was updated for the weekend.",
    "Research note {i}: a paper about database indexing was saved for later reading.",
)


def build_neutral_pool(count: int = 300) -> list[str]:
    """Deterministic neutral distractor documents used to pad rerank pools."""
    return [NEUTRAL_TEMPLATES[i % len(NEUTRAL_TEMPLATES)].format(i=i) for i in range(count)]


def build_journal(target_chars: int = 180_000, generator: dict | None = None) -> tuple[str, list[str]]:
    """Build the long synthetic journal: needle facts surrounded by filler.

    Returns ``(journal_text, needle_facts)``. Needle placement follows the
    fractional positions in ``generator.json`` so needles land from the
    beginning through the end of the text; any needle truncated by the final
    size cut is appended whole.
    """
    gen = generator or load_journal_generator()
    facts = list(gen["needle_facts"])
    filler = list(gen["filler_sentences"])
    positions = [int(target_chars * p) for p in gen["needle_positions"]]

    parts: list[str] = []
    placed = 0
    while sum(map(len, parts)) < target_chars:
        current = sum(map(len, parts))
        if placed < len(facts) and current >= positions[placed]:
            parts.append("\n\n" + facts[placed] + "\n\n")
            placed += 1
        else:
            parts.append(filler[len(parts) % len(filler)] + " ")
    journal = "".join(parts)[:target_chars]
    for fact in facts:
        if fact not in journal:
            journal += "\n\n" + fact
    return journal, facts


def build_journal_chunks(target_chars: int = 180_000, max_chars: int = 3000) -> tuple[list[dict], list[str], str]:
    journal, facts = build_journal(target_chars)
    return chunk_text(journal, max_chars), facts, journal
